name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup ESLint
        run: |
          npm install --save-dev eslint@8.56.0 eslint-plugin-react@7.33.2 eslint-plugin-react-hooks@4.6.0 eslint-plugin-import@2.29.1 eslint-config-prettier@9.1.0
          [ -f .eslintrc.json ] || wget https://raw.githubusercontent.com/borluv/linters-configuration/main/react-sass/.eslintrc.json
      - name: ESLint Report
        run: npx eslint . --ext js,jsx
  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@16.2.1 stylelint-config-standard-scss@13.0.0 stylelint-config-css-modules@4.4.0
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/borluv/linters-configuration/main/react-sass/.stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.scss"
  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi
